
export const learningTips: string[] = [
  "Use the '5-Minute Rule'. Tell yourself you'll only work on a task for 5 minutes. Getting started is the hardest part.",
  "Body Doubling: Study with a friend, even if you work on different things. Their quiet presence can improve focus.",
  "Externalize your thoughts. Use this app's 'Brain Dump' to offload distracting ideas without losing them.",
  "Turn tasks into a game. How many 'Focus Points' can you earn today? Compete against your past self.",
  "Fidget! Using a fidget toy can occupy your need for stimulation, freeing up your brain to focus on the task.",
  "Wear noise-canceling headphones, even with no music. It signals 'do not disturb' to others and your own brain.",
  "Break it down further. If a sub-task feels too big, break it down again until it feels ridiculously easy.",
  "Schedule breaks, don't just take them when you're tired. This prevents burnout and respects your brain's energy limits.",
  "Set a 'launchpad' the night before. Have everything for your first task (books, notes) ready to go.",
  "Change your scenery. Studying in a new location can provide the novelty your brain craves and boost focus.",
  "Use visual aids. Color-code your tasks by subject or urgency to make your plan immediately understandable.",
  "Talk it out. Explain a concept out loud to yourself, a pet, or a friend. It engages more of your brain.",
  "Hydrate and snack smart. Your brain needs fuel. Keep water and protein-rich snacks handy to avoid energy crashes.",
  "Pair a boring task with something you enjoy, like listening to a specific type of music (without lyrics!).",
  "Work with your energy levels. Tackle your most demanding tasks during your personal 'peak' brain hours.",
  "Set clear boundaries. Let friends and family know your dedicated 'sprint' times to minimize interruptions.",
  "Forgive yourself for getting distracted. Acknowledge it without judgment and gently guide your focus back.",
  "Use the visual timer! Seeing time pass makes it more concrete and helps you stay on track.",
  "Give every task a 'home'. Don't leave things in a vague 'to-do' state; put them in a column so you know their status.",
  "Celebrate small wins. Finishing a sub-task or a Pomodoro session is a real accomplishment. Acknowledge it!",
  "Create a 'Done' list. At the end of the day, look at what you *did* accomplish instead of focusing on what you didn't.",
  "Incorporate movement. A quick 2-minute stretch or walk between Pomodoros can reset your focus.",
  "Set just one or two 'Must-Do' tasks for the day. Everything else is a bonus. This reduces overwhelm.",
  "Use the 'First Step' AI feature. It's specifically designed to break the inertia of procrastination.",
  "Limit choices. If you have too many tasks, it can lead to decision paralysis. Pick one priority and hide the rest.",
  "Connect tasks to your goals. Remind yourself *why* you are doing this boring task. What's the bigger picture?",
  "Create novelty. Try a new note-taking method, use different colored pens, or turn your notes into a mind map.",
  "Use deadlines to your advantage. A little bit of urgency can be a powerful motivator for the ADHD brain.",
  "Before you stop a task, write down the very next step. This makes it much easier to pick it back up later.",
  "Reward yourself. Plan a specific, enjoyable reward for when you complete a major task or a study session."
];
